### ISSUE TITLE
How to change voltage for GPU?

### ISSUE THREAD

**Issue by jyuuren** [rzc0d3r/Mediatek-Voltage-Control#1]

**Comment by jyuuren** [comment]
Also i get this error when using with Xiaomi 11T (MT6893): "Your CPU or OC not supported!!!".

**Comment by rzc0d3r** [comment]
Hello! Thank you for your feedback!
Try running this version and attach a screenshot of the terminal here.
[https://anonfiles.com/u462m41fz5/rzc0d3r_MVControl_v1_3_Debug_py](url)

**Comment by jyuuren** [comment]
I will, thanks.

**Comment by rzc0d3r** [comment]
> 

that's the point of the update. Now the menus are dynamically changed for each device

**Comment by rzc0d3r** [comment]
You can certainly try to help me expand the functionality, but it seems impossible to me.

**Comment by rzc0d3r** [comment]
use root explorer. And search the /proc folder by the name "eem"

**Comment by rzc0d3r** [comment]
and send me the results (screenshot)

**Comment by jyuuren** [comment]
![Screenshot_2023-07-30-17-44-39-577_com mixplorer](https://github.com/rzc0d3r/Mediatek-Voltage-Control/assets/73755597/2a64f9c6-fb38-40c8-9923-6f8996a35db4)

**Comment by rzc0d3r** [comment]
can you please screenshot the EEM_DET_BL folder?

**Comment by jyuuren** [comment]
![Screenshot_2023-08-01-03-35-19-850_com mixplorer](https://github.com/rzc0d3r/Mediatek-Voltage-Control/assets/73755597/e874e698-dfe5-48fe-9fe4-f9b1dfc7053b)

**Comment by rzc0d3r** [comment]
I will add BL but without decryption as there is no kernel source.
